apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autobot-ingress
  namespace: autobot-studio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: autobot.local  # Add to /etc/hosts: minikube_ip autobot.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autobot-service
                port:
                  number: 80
